### ISSUE TITLE
Human-facing project UI command depends on unset CLAUDE_PLUGIN_ROOT

### ISSUE THREAD

**Issue by max-miller1204** [max-miller1204/stepstone#27]
## Problem

The Claude plugin instructs the assistant to return this command for a human to paste into the repository's interactive terminal:

```sh
node "${CLAUDE_PLUGIN_ROOT}/dist/cli.js" project ui
```

`CLAUDE_PLUGIN_ROOT` is available to the plugin process but is not necessarily exported into the human's interactive shell. When it is unset, the path resolves to `/dist/cli.js` and Node fails with `MODULE_NOT_FOUND`.

This was observed in Fish, but it is not Fish-specific. An unset variable produces the same invalid absolute path in Bash and Zsh.

## Reproduction

From an interactive shell where `CLAUDE_PLUGIN_ROOT` is unset:

```console
$ node "$CLAUDE_PLUGIN_ROOT/dist/cli.js" project ui
Error: Cannot find module '/dist/cli.js'
```

## Expected behavior

The copy-paste command should work independently of plugin-process-only environment variables. For the published package, the portable command is:

```sh
npx -y stepstone@latest project ui
```

## Suggested fix

Update the board-launch instruction or generated human-facing command to emit the portable `npx` invocation, or otherwise provide a concrete executable path that remains valid in the user's terminal.
